import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";

import { ThemeProvider } from "@repo/ui/components/theme/provider";
import { Toaster } from "@repo/ui/components/ui/sonner";
import { ClerkClientProvider } from "@/providers/clerk-client-provider";
import { ConvexClientProvider } from "@/providers/convex-client-provider";

import "@repo/ui/globals.css";

const fontSans = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const fontMono = Roboto_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Konvo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fontSans.variable} ${fontMono.variable} font-sans antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <ClerkClientProvider>
            <ConvexClientProvider>
              {children}
              <Toaster position="top-center" />
            </ConvexClientProvider>
          </ClerkClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
