import type { Metadata } from "next";
import { DM_Mono, Inter } from "next/font/google";

import { ThemeProvider } from "@repo/ui/components/theme/provider";
import { ConvexClientProvider } from "@/providers/convex-client-provider";

import "@repo/ui/globals.css";
import { JotaiProvider } from "@/providers/jotai-provider";

const fontSans = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const fontMono = DM_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: ["300", "400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fontSans.variable} ${fontMono.variable} font-sans antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ConvexClientProvider>
            <JotaiProvider>{children}</JotaiProvider>
          </ConvexClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
